language: python
sudo: false
notifications:
  email: false
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
before_install:
- ! '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_6e98b3e8e789_key -iv $encrypted_6e98b3e8e789_iv -in .env.enc -out .env -d || true'
install:
- pip install -r requirements-dev.txt
- pip install pylint
- pip install codecov
- pip install git+git://github.com/watson-developer-cloud/python-sdk.git#egg=watson-developer-cloud
script:
- sh pylint.sh
- py.test test --cov=watson_developer_cloud
after_success:
- codecov
- docs/publish.sh
