environment:

  matrix:

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:

  # Install Python (from the official .msi of https://python.org) and pip when
  # not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

  # Prepend newly installed Python to the PATH of this build
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  - "python -m pip install --upgrade pip"

  # Install the build dependencies of the project.
  - "pip install -r requirements-dev.txt"

build: off

test_script:

  - ps: py.test --reruns 3 --cov=watson_developer_cloud

deploy: off

matrix:
  fast_finish: true